# Generated by Django 2.1.3 on 2018-12-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20181209_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField()),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
    ]
